import Foundation
import Testing

@testable import JobsKit

/// The cross-language drift guard: fit-parity.json is generated by running the
/// site's ACTUAL matchFit.ts over the same fixtures (ios/tools/
/// emit-fit-parity.mts), and this suite asserts the Swift port reproduces
/// every answer — every taxonomy keyword against the boundary corpus, every
/// parseQualName reading, a full matchJob ladder grid, and complete ordered
/// bucketJobs runs over 406 live rows.
@Suite struct FitParityTests {
    struct Parity: Decodable {
        struct KeywordCase: Decodable {
            let t: String
            let m: Bool
        }
        struct KeywordEntry: Decodable {
            let keyword: String
            let cases: [KeywordCase]
        }
        struct ParseCase: Decodable {
            let input: String
            let fields: [String]
        }
        struct Profile: Decodable {
            let qualLevel: Int
            let fields: [String]
            let years: Int?

            var swift: FitProfile { FitProfile(qualLevel: qualLevel, fields: fields, years: years) }
        }
        struct MatchCase: Decodable {
            let profile: Profile
            let req: JobReq?
            let bucket: String
            let score: Int
        }
        struct BucketCase: Decodable {
            let profile: Profile
            let strong: [String]
            let possible: [String]
            let stretch: [String]
            let unscored: [String]
            let aboveCount: Int
        }

        let rulesVersion: Int
        let keywords: [KeywordEntry]
        let parseQualName: [ParseCase]
        let matchJob: [MatchCase]
        let bucketJobs: [BucketCase]
    }

    static let parity: Parity = try! JSONDecoder().decode(
        Parity.self, from: Fixtures.data("fit-parity.json"))

    @Test func fixtureMatchesShippedRulesVersion() {
        #expect(Self.parity.rulesVersion == Fixtures.requirements.version)
    }

    @Test func keywordCompilerAgreesOnEveryCase() throws {
        var mismatches: [String] = []
        var matched = 0
        var unmatched = 0
        for entry in Self.parity.keywords {
            let pattern = try #require(KeywordPattern(entry.keyword))
            for c in entry.cases {
                if pattern.matches(c.t) != c.m {
                    mismatches.append("\(entry.keyword) on \(c.t): expected \(c.m)")
                }
                if c.m { matched += 1 } else { unmatched += 1 }
            }
        }
        #expect(mismatches == [])
        // The corpus must exercise both answers, or agreement proves nothing.
        #expect(matched > 0)
        #expect(unmatched > 0)
    }

    @Test func parseQualNameAgreesOnEveryInput() {
        for c in Self.parity.parseQualName {
            let fields = FitMatcher.parseQualName(c.input, taxonomy: Fixtures.requirements.taxonomy)
            #expect(fields == c.fields, "parseQualName(\(c.input))")
        }
    }

    @Test func matchJobAgreesAcrossTheLadderGrid() {
        for c in Self.parity.matchJob {
            let (placement, score) = FitMatcher.matchJob(user: c.profile.swift, req: c.req)
            #expect(placement.rawValue == c.bucket, "bucket for \(c.profile) vs \(String(describing: c.req))")
            #expect(score == c.score, "score for \(c.profile) vs \(String(describing: c.req))")
        }
    }

    @Test func bucketJobsReproducesOrderedBucketsOverTheLiveSnapshot() {
        // The generator pools ZA rows in fixture order — the /fit/ island's
        // default scope.
        let pool = Fixtures.jobs.filter { $0.country == "ZA" }
        for c in Self.parity.bucketJobs {
            let out = FitMatcher.bucketJobs(
                user: c.profile.swift, rows: pool, reqs: Fixtures.requirements.jobs)
            #expect(out.strong.map(\.id) == c.strong)
            #expect(out.possible.map(\.id) == c.possible)
            #expect(out.stretch.map(\.id) == c.stretch)
            #expect(out.unscored.map(\.id) == c.unscored)
            #expect(out.aboveCount == c.aboveCount)
        }
    }

    @Test func bucketJobsIsByteDeterministic() throws {
        let pool = Fixtures.jobs.filter { $0.country == "ZA" }
        let user = FitProfile(qualLevel: 3, fields: ["accounting"], years: 2)

        func run() throws -> Data {
            let out = FitMatcher.bucketJobs(user: user, rows: pool, reqs: Fixtures.requirements.jobs)
            let ids = [
                out.strong.map(\.id), out.possible.map(\.id),
                out.stretch.map(\.id), out.unscored.map(\.id),
            ]
            return try JSONEncoder().encode(ids)
        }

        #expect(try run() == run())
    }
}
